/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/air-conditioner-room/': RouteRecordInfo<'/air-conditioner-room/', '/air-conditioner-room', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/chengdu-song': RouteRecordInfo<'/posts/chengdu-song', '/posts/chengdu-song', Record<never, never>, Record<never, never>>,
    '/posts/linux-bond': RouteRecordInfo<'/posts/linux-bond', '/posts/linux-bond', Record<never, never>, Record<never, never>>,
    '/posts/linux-pxe': RouteRecordInfo<'/posts/linux-pxe', '/posts/linux-pxe', Record<never, never>, Record<never, never>>,
    '/posts/openwrt-ban-ip': RouteRecordInfo<'/posts/openwrt-ban-ip', '/posts/openwrt-ban-ip', Record<never, never>, Record<never, never>>,
    '/posts/start-here': RouteRecordInfo<'/posts/start-here', '/posts/start-here', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
